{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "linux-sgx-debug",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ynpnrwttbnazrjru2alvsadliq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "linux-sgx-debug-1.1.jar",
          "url": "linux-sgx-debug-1.1.jar",
          "size": 6008114,
          "sha512": "bad649bfe4039bef2e619aae62095de7af16a4abff756398b9284bfae33fc8c5f2b4455e2e45f7c0a0436a10b4faf1161696620cb2b40818e28a02edf6a46f1a",
          "sha256": "6b5441b9500e1782116b277cc515ae736cf0b55782663b9df4d32595f325c59b",
          "sha1": "0ecd9aa166f907fc81e04e7fdcb9bf034d49fafe",
          "md5": "57cb3233a57acdc929b0579bdc165807"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "linux-sgx-debug-1.1.jar",
          "url": "linux-sgx-debug-1.1.jar",
          "size": 6008114,
          "sha512": "bad649bfe4039bef2e619aae62095de7af16a4abff756398b9284bfae33fc8c5f2b4455e2e45f7c0a0436a10b4faf1161696620cb2b40818e28a02edf6a46f1a",
          "sha256": "6b5441b9500e1782116b277cc515ae736cf0b55782663b9df4d32595f325c59b",
          "sha1": "0ecd9aa166f907fc81e04e7fdcb9bf034d49fafe",
          "md5": "57cb3233a57acdc929b0579bdc165807"
        }
      ]
    }
  ]
}
