{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-enclave-debug",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ynpnrwttbnazrjru2alvsadliq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-enclave-debug-1.1.jar",
          "url": "native-enclave-debug-1.1.jar",
          "size": 38387922,
          "sha512": "db73c201e746d7abfdb0605ac66dc9c4459cc74cbfade8626e439db6df2a0a358227512b78fd7e550585fa2c027f033ead4da75320496217cf0fa5d92f91ecab",
          "sha256": "fcc828d8385855ad5a08cbd29ddb256429076f4126228ac80829180d23aa87ff",
          "sha1": "d103026da75a0f18ce762431ed92c7b9a5eaf83a",
          "md5": "cd04e206d65534aec1471490aed5a427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-enclave-debug-1.1.jar",
          "url": "native-enclave-debug-1.1.jar",
          "size": 38387922,
          "sha512": "db73c201e746d7abfdb0605ac66dc9c4459cc74cbfade8626e439db6df2a0a358227512b78fd7e550585fa2c027f033ead4da75320496217cf0fa5d92f91ecab",
          "sha256": "fcc828d8385855ad5a08cbd29ddb256429076f4126228ac80829180d23aa87ff",
          "sha1": "d103026da75a0f18ce762431ed92c7b9a5eaf83a",
          "md5": "cd04e206d65534aec1471490aed5a427"
        }
      ]
    }
  ]
}
