{
  "formatVersion": "1.1",
  "component": {
    "group": "com.r3.conclave",
    "module": "native-enclave-simulation",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ynpnrwttbnazrjru2alvsadliq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-enclave-simulation-1.1.jar",
          "url": "native-enclave-simulation-1.1.jar",
          "size": 38392494,
          "sha512": "7892fc48d22ed6d4505c22890457ed49f4c650af2f36fb5b781d0271189badc143257cb42fcc30e36999419568ed32542d6b1ac1e1e25b6540fcf5637ee35b61",
          "sha256": "ba8ddbc6bb2f541149f0ef28f50107af900999b5931cfc9de49010fa8928f736",
          "sha1": "e649423ed4fb9db49eb0d6534af652eb315b2155",
          "md5": "482796030b30f93e805c0e5824e4ecdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-enclave-simulation-1.1.jar",
          "url": "native-enclave-simulation-1.1.jar",
          "size": 38392494,
          "sha512": "7892fc48d22ed6d4505c22890457ed49f4c650af2f36fb5b781d0271189badc143257cb42fcc30e36999419568ed32542d6b1ac1e1e25b6540fcf5637ee35b61",
          "sha256": "ba8ddbc6bb2f541149f0ef28f50107af900999b5931cfc9de49010fa8928f736",
          "sha1": "e649423ed4fb9db49eb0d6534af652eb315b2155",
          "md5": "482796030b30f93e805c0e5824e4ecdc"
        }
      ]
    }
  ]
}
